[connections.snowflake]
account = "GQVCGRI-PWB97866"
user = "SASHISRI"
password = "ILuvPecanPie2!"
role = "SYSADMIN"
warehouse = "COMPUTER-WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
